#!/usr/bin/env python

import redis
import json
import sys
import os
from gi.repository import Notify

def main():
    Notify.init("notistream")

    if len(sys.argv) < 2:
        f = open(os.path.expanduser('~/.notistream/config.json'))
    else:
        f = open(sys.argv[1])

    config = json.load(f)

    r = redis.Redis(host=config['host'], port=config['port'])
    ps = r.pubsub()
    ps.subscribe(config['channels'])

    for msg in ps.listen():
        if msg['type'] == 'message':
            n = Notify.Notification.new('Notistream', msg['data'], None)
            n.show()

if __name__ == '__main__':
    main()
